# Generated by Django 3.0.7 on 2020-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users')),
                ('text', models.TextField()),
                ('tags', models.CharField(choices=[('Ed', 'education'), ('Tr', 'travel'), ('Te', 'Technology'), ('Bo', 'Books'), ('De', 'Default')], default='De', max_length=2)),
                ('updated_stamp', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
